AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'

Metrics/LineLength:
  Max: 140

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ModuleLength:
  Max: 175

Style/RegexpLiteral:
  EnforcedStyle: percent_r
  Enabled: True

Layout/EmptyLinesAroundArguments:
  Enabled: False
