source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
# gem 'sinatra-authentication'
gem 'activerecord', '4.2.11', require: 'active_record'
gem 'bcrypt'
gem 'github_changelog_generator'
gem 'mcollective-client'
gem 'puma'
gem 'puppet_forge', '2.2.8'
gem 'rb-readline'
gem 'r10k'
gem 'rake'
gem 'require_all'
gem 'rocket-chat-notifier'
gem 'shotgun'
gem 'sidekiq', '< 6.0.0'
gem 'sinatra-activerecord', require: 'sinatra/activerecord'
gem 'slack-notifier'
gem 'sqlite3', '1.3.13'
gem 'thin'
gem 'tux'
gem 'warden'

group :development do
  gem 'debase'
  gem 'fustigit'
  gem 'pry'
  gem 'pry-byebug'
  gem 'rack-console'
  gem 'rubocop'
  gem 'ruby-debug-ide'
  gem 'ruby-git'
  gem 'vanagon', '0.15.25'
  gem 'yard', '>= 0.9.20'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'coveralls'
  gem 'rack-test'
  gem 'rspec'
  gem 'simplecov'
  gem 'simplecov-console'
  gem 'webmock'
end
